### PR TITLE
[issue][94] Use :value and @input instead of v-model on select

### LINKED ISSUE #94: Keyboard input not working on some VInput text fields and email fields properly
With the latest release (0.7.2), VInput with a standard text field no longer allows typing with the keyboard. I tested it out on Chrome, Safari, and Firefox on Mac to make sure it wasn't a browser quirk.

I was able to see it also affects your documentation page here when you attempt to type into the "features" field in the Description section: https://vuetensils.stegosource.com/components/input.html#description

Using type=email, it also appears the first letter typed will not appear. (e.g. if you type "12" it will only display "2"). I found this one on the documentation page as well. Hopefully that helps narrow it down a little!

### PR DESCRIPTION
**Pull request by Tintef**
Closes #94 

Changes:
- Stop using `v-model` on select inputs
- Manually bind the `localValue` and use the `@input` listener

### CODE REVIEW

File: src/components/VInput/VInput.vue [hunk 1]
```diff
@@ -49,7 +49,7 @@
         :checked="localValue === undefined ? $attrs.checked : localValue"
         v-bind="bind"
         @change="localValue = $event.target.checked"
-        @blur.once.once="dirty = true"
+        @blur.once="dirty = true"
```
Comment (Stegosource) [inline src/components/VInput/VInput.vue:52]: It's funny. I think this must be getting added by some auto formatter because I swear I've removed it like 3 times now. That or Im going crazy.

File: src/components/VInput/VInput.vue [hunk 2]
```diff
@@ -69,7 +69,8 @@
       <select
         v-if="'select' === $attrs.type"
         ref="input"
-        v-model="localValue"
+        :value="localValue"
+        @input.prevent="localValue = $event.target.value"
```
Comment (Stegosource) [inline src/components/VInput/VInput.vue:73]: This looks fine, but why did you add the `prevent` modifier?

Comment (Tintef) [reply src/components/VInput/VInput.vue:73]: Not a real reason to be honest

Comment (Stegosource) [reply src/components/VInput/VInput.vue:73]: Ok. Wasn't sure if this was related to the bug. I'll merge this in, but I'll have to manually create the next release. I still don't have the release system automated.
